usage cache:Avoid logging replication config missing error
Some stale entries can be reported on startup - avoid logging these.
```
API: SYSTEM()
Time: 12:24:04 PST 11/19/2021
DeploymentID: d9db8746-70ee-47b3-96b2-d9247a8da126
Error: The replication configuration was not found: / (cmd.BucketReplicationConfigNotFound)
       5: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       4: internal/logger/logonce.go:92:logger.LogOnceIf()
       3: cmd/data-usage-cache.go:941:cmd.(*dataUsageCache).load()
       2: cmd/erasure.go:366:cmd.erasureObjects.nsScanner()
       1: cmd/erasure-server-pool.go:533:cmd.(*erasureServerPools).NSScanner.func2()
```